// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniCommerce.Persistence.DbContexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MiniCommerce.Persistence.Migrations
{
    [DbContext(typeof(MiniCommerceDbContext))]
    [Migration("20220614122605_mig_1")]
    partial class mig_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Brand");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LCW VISION"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "XSIDE"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LCW CLASSIC"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LCW CASUAL"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LCW BASIC"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LCW FORMAL"
                        });
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            Name = "Mont"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            Name = "Hırka ve Süveter"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            Name = "Kazak"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Keten Rahatlığı",
                            Name = "Gömlek"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Güneşin keyfini çıkar",
                            Name = "Tişört"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Favorilerini seç, en trend ürünleri keşfet",
                            Name = "Sweatshirt"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sezonun en hit parçalarını keşfet",
                            Name = "Jean"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "demodemodemo",
                            Name = "Elbise"
                        });
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Color");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Siyah"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sarı"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kırmızı"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Beyaz"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pembe"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Yeşil"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bej"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mavi"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gri"
                        });
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = false,
                            Price = 50.00m,
                            ProductId = 6,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = false,
                            Price = 250.00m,
                            ProductId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = false,
                            Price = 230.00m,
                            ProductId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = false,
                            Price = 280.00m,
                            ProductId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = false,
                            Price = 271.00m,
                            ProductId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = false,
                            Price = 85.00m,
                            ProductId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = false,
                            Price = 70.00m,
                            ProductId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = false,
                            Price = 90.00m,
                            ProductId = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = true,
                            Price = 92.00m,
                            ProductId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = true,
                            Price = 85.00m,
                            ProductId = 6,
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = true,
                            Price = 205.00m,
                            ProductId = 7,
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = false,
                            Price = 78.00m,
                            ProductId = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = false,
                            Price = 95.00m,
                            ProductId = 9,
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = false,
                            Price = 56.00m,
                            ProductId = 10,
                            UserId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = false,
                            Price = 76.00m,
                            ProductId = 11,
                            UserId = 4
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = false,
                            Price = 63.00m,
                            ProductId = 12,
                            UserId = 4
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = false,
                            Price = 84.00m,
                            ProductId = 12,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("ColorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsOfferable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UsageId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ColorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UsageId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 4,
                            CategoryId = 1,
                            ColorId = 7,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            ImageUrl = "LCWCASUALBejMont.jpg",
                            IsOfferable = true,
                            IsSold = false,
                            Name = "Slim Fit Kapüşonlu İnce Erkek Kanguru Mont",
                            Price = 309.99m,
                            Stock = 400,
                            UsageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 4,
                            CategoryId = 1,
                            ColorId = 5,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            ImageUrl = "LCWCASUALPembeMont.jpg",
                            IsOfferable = true,
                            IsSold = false,
                            Name = "Dik Yaka Düz Uzun Kollu İnce Kadın Mont",
                            Price = 319.99m,
                            Stock = 400,
                            UsageId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 5,
                            CategoryId = 2,
                            ColorId = 4,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            ImageUrl = "LCWBASICBeyazHirka.jpg",
                            IsOfferable = true,
                            IsSold = false,
                            Name = "Bisiklet Yaka Düz Uzun Kollu Viskon Kadın Hırka",
                            Price = 59.99m,
                            Stock = 400,
                            UsageId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            CategoryId = 2,
                            ColorId = 6,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            ImageUrl = "XSIDEYeşilHırka.jpg",
                            IsOfferable = true,
                            IsSold = false,
                            Name = "Dik Yaka Düz Uzun Kollu Crop Kadın Hırka",
                            Price = 109.99m,
                            Stock = 400,
                            UsageId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            CategoryId = 3,
                            ColorId = 2,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            ImageUrl = "LCWVISIONSarıKazak.jpg",
                            IsOfferable = true,
                            IsSold = false,
                            Name = "Bisiklet Yaka Uzun Kollu Erkek Triko Kazak",
                            Price = 139.99m,
                            Stock = 400,
                            UsageId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 4,
                            CategoryId = 3,
                            ColorId = 3,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            ImageUrl = "LCWCASUALKirmiziKazak.jpg",
                            IsOfferable = true,
                            IsSold = false,
                            Name = "Bisiklet Yaka Düz Uzun Kollu Kadın Triko Kazak",
                            Price = 99.99m,
                            Stock = 400,
                            UsageId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 6,
                            CategoryId = 4,
                            ColorId = 8,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            ImageUrl = "LCWFORMALMaviGomlek.jpg",
                            IsOfferable = true,
                            IsSold = false,
                            Name = "Slim Fit Uzun Kollu Poplin Erkek Gömlek",
                            Price = 289.99m,
                            Stock = 400,
                            UsageId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 1,
                            CategoryId = 4,
                            ColorId = 4,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            ImageUrl = "LCWVISIONBeyazGomlek.jpg",
                            IsOfferable = true,
                            IsSold = false,
                            Name = "Önden Düğme Kapamalı Düz Kısa Kollu Poplin Kadın Gömlek",
                            Price = 149.99m,
                            Stock = 400,
                            UsageId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            CategoryId = 5,
                            ColorId = 2,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            ImageUrl = "XSIDESarıTisort.jpg",
                            IsOfferable = true,
                            IsSold = false,
                            Name = "Bisiklet Yaka Baskılı Kısa Kollu Pamuklu Crop Kadın Tişört",
                            Price = 99.99m,
                            Stock = 400,
                            UsageId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 4,
                            CategoryId = 5,
                            ColorId = 1,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            ImageUrl = "LCWCASUALSiyahTisort.jpg",
                            IsOfferable = true,
                            IsSold = false,
                            Name = "Polo Yaka Kısa Kollu Pike Erkek Tişört",
                            Price = 149.99m,
                            Stock = 400,
                            UsageId = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 2,
                            CategoryId = 6,
                            ColorId = 8,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            ImageUrl = "XSIDEMaviSweatShirt.jpg",
                            IsOfferable = true,
                            IsSold = false,
                            Name = "Kapüşon Yaka Nakışlı Uzun Kollu Kadın Sweatshirt",
                            Price = 89.99m,
                            Stock = 400,
                            UsageId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 2,
                            CategoryId = 6,
                            ColorId = 6,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            ImageUrl = "XSIDEYeşilSweatShirt.jpg",
                            IsOfferable = true,
                            IsSold = false,
                            Name = "Kapüşonlu Uzun Kollu Baskılı Erkek Sweatshirt",
                            Price = 199.99m,
                            Stock = 400,
                            UsageId = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 4,
                            CategoryId = 7,
                            ColorId = 9,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            ImageUrl = "LCWCASULGriJean.jpg",
                            IsOfferable = true,
                            IsSold = false,
                            Name = "750 Slim Fit Erkek Jean Pantolon",
                            Price = 189.99m,
                            Stock = 400,
                            UsageId = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 1,
                            CategoryId = 8,
                            ColorId = 6,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            ImageUrl = "LCWVISIONYesilElbise.jpg",
                            IsOfferable = true,
                            IsSold = false,
                            Name = "Halter Yaka Düz Kolsuz Kadın Elbise",
                            Price = 199.99m,
                            Stock = 400,
                            UsageId = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 3,
                            CategoryId = 8,
                            ColorId = 5,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soğuk kış günleri üşümeyin diye",
                            ImageUrl = "LCWCASUALPembeElbise.jpg",
                            IsOfferable = true,
                            IsSold = false,
                            Name = "U Yaka Düz Askılı A Kesim Poplin Kadın Elbise",
                            Price = 199.99m,
                            Stock = 400,
                            UsageId = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.Usage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Usage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Yeni"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Az Kullanılmış"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Çok Kullanılmış"
                        });
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Address = "İzmir",
                            ConcurrencyStamp = "a7f3759a-a4f8-416e-b100-ced8454ef3aa",
                            Email = "kutay@seeddata.com",
                            EmailConfirmed = true,
                            FirstName = "Kutay",
                            LastName = "Demirel",
                            LockoutEnabled = false,
                            NormalizedEmail = "KUTAY@SEEDDATA.COM",
                            NormalizedUserName = "KUTAY@SEEDDATA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEN3JGm8XQQAoQu6mgJLFUQcJAtwY4bStyhByi8RCuzzOI9xAj2SfsJwliWvGtkkt4Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4401613d-606e-4aaf-9b09-e9d92ed2b2c6",
                            TwoFactorEnabled = false,
                            UserName = "kutay@seeddata.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Address = "İzmir",
                            ConcurrencyStamp = "5a242f6c-9876-49db-88b6-50b09974893a",
                            Email = "lale@seeddata.com",
                            EmailConfirmed = true,
                            FirstName = "Lale",
                            LastName = "Gezer",
                            LockoutEnabled = false,
                            NormalizedEmail = "LALE@SEEDDATA.COM",
                            NormalizedUserName = "LALE@SEEDDATA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELYdatN3QKRcMWghR0BhsbX6IoZmyqKM/HdZCEggPu0r7wDjIq18fhfCM8v9th69Bw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e3cfc8fd-6d2d-48b3-9204-18e5eb3a8e8a",
                            TwoFactorEnabled = false,
                            UserName = "lale@seeddata.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Address = "İzmir",
                            ConcurrencyStamp = "81d55b73-e60a-4961-ab6e-7cab3d34ff57",
                            Email = "mehmet@seeddata.com",
                            EmailConfirmed = true,
                            FirstName = "Mehmet",
                            LastName = "Turan",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHMET@SEEDDATA.COM",
                            NormalizedUserName = "MEHMET@SEEDDATA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEx3FGuTJin2ncOlKo/inweajdTsT4lAt+9La5GblPHBTcFxZ8XRuYB4DdYw+z38dQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "449dfd28-0093-444d-bdfa-0da59a943e31",
                            TwoFactorEnabled = false,
                            UserName = "mehmet@seeddata.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            Address = "İzmir",
                            ConcurrencyStamp = "6f8565d3-2037-42d7-ab99-29e1c4e817a4",
                            Email = "sezer@seeddata.com",
                            EmailConfirmed = true,
                            FirstName = "Sezer",
                            LastName = "Yılmaz",
                            LockoutEnabled = false,
                            NormalizedEmail = "SEZER@SEEDDATA.COM",
                            NormalizedUserName = "SEZER@SEEDDATA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGYiaJ6/kk/fopPmYYqDTyXwtCwesPqlVT5B7MOmhmYJsKzIQK9aorObYDBeVrT6SA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5cb0b262-bbec-46b7-acb6-db19c77739b0",
                            TwoFactorEnabled = false,
                            UserName = "sezer@seeddata.com"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            Address = "İzmir",
                            ConcurrencyStamp = "3cff518b-9468-4bc0-a530-1695957d8c6e",
                            Email = "mert@seeddata.com",
                            EmailConfirmed = true,
                            FirstName = "Mert",
                            LastName = "Durmaz",
                            LockoutEnabled = false,
                            NormalizedEmail = "MERT@SEEDDATA.COM",
                            NormalizedUserName = "MERT@SEEDDATA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEC5bG1u8aH68/3ZUEIVl+tL37fJ0EJ5viKv2F2KSCytncKs0SUMTOame6mLb2Ey1kA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5cc562db-bbaf-42e5-bfd1-f67088ec4996",
                            TwoFactorEnabled = false,
                            UserName = "mert@seeddata.com"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            Address = "İzmir",
                            ConcurrencyStamp = "8eb3ffc6-dbe2-4f05-84af-4bf711f2b1a6",
                            Email = "kaan@seeddata.com",
                            EmailConfirmed = true,
                            FirstName = "Kaan",
                            LastName = "Kara",
                            LockoutEnabled = false,
                            NormalizedEmail = "KAAN@SEEDDATA.COM",
                            NormalizedUserName = "KAAN@SEEDDATA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJlvcvNZJm7UxZr2JKBYIhiEXo+Flj9KD0xsHspn/BhbZ653BgGcf6gKRVzgYUby/A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2b064e3c-6964-40a4-baed-75a5cfabc066",
                            TwoFactorEnabled = false,
                            UserName = "kaan@seeddata.com"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            Address = "İzmir",
                            ConcurrencyStamp = "58303d31-ce45-4497-9469-894c3022e6bb",
                            Email = "bora@seeddata.com",
                            EmailConfirmed = true,
                            FirstName = "Bora",
                            LastName = "Kırılmaz",
                            LockoutEnabled = false,
                            NormalizedEmail = "BORA@SEEDDATA.COM",
                            NormalizedUserName = "BORA@SEEDDATA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEE8ZDxjoaLhs2wVS1rGnIVXrNsFR70M1fUpSn0FgsY0NQALWKgXd+ejKCPxYatO3UA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6a604bd2-4e70-4f7c-bbe0-a2d4c717511e",
                            TwoFactorEnabled = false,
                            UserName = "bora@seeddata.com"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            Address = "İzmir",
                            ConcurrencyStamp = "5b3b64a5-04b3-4f99-a3b3-f7cdaf6b84ef",
                            Email = "ahmet@seeddata.com",
                            EmailConfirmed = true,
                            FirstName = "Ahmet",
                            LastName = "Yıkılmaz",
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMET@SEEDDATA.COM",
                            NormalizedUserName = "AHMET@SEEDDATA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGoRkOTXH2JRY8oVzwaWVIZreKC8SVwYK93GEWQOJrabXE7ziywmXZgKpGPLXM6jLQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cfb7dcdd-05cf-4d4f-9dd6-1e6ba372a3d0",
                            TwoFactorEnabled = false,
                            UserName = "ahmet@seeddata.com"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            Address = "İzmir",
                            ConcurrencyStamp = "d4df4d6b-799b-4131-977d-6e8b346a32a4",
                            Email = "fatma@seeddata.com",
                            EmailConfirmed = true,
                            FirstName = "Fatma",
                            LastName = "Gedik",
                            LockoutEnabled = false,
                            NormalizedEmail = "FATMA@SEEDDATA.COM",
                            NormalizedUserName = "FATMA@SEEDDATA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJSmxm4futF3PibY/mkVy6d87lm4EIAvNHoHkQr6q+5dP3pbFe/laHFGzaxm255EQQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ab84c1f5-e8db-4b1f-ad3e-63a4bb3ccd27",
                            TwoFactorEnabled = false,
                            UserName = "fatma@seeddata.com"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            Address = "İzmir",
                            ConcurrencyStamp = "b84ef24c-bc9d-41c2-9b89-562acb1c2ac9",
                            Email = "ezgi@seeddata.com",
                            EmailConfirmed = true,
                            FirstName = "Ezgi",
                            LastName = "Dene",
                            LockoutEnabled = false,
                            NormalizedEmail = "EZGI@SEEDDATA.COM",
                            NormalizedUserName = "EZGI@SEEDDATA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHCiZWXq7/l3TRW2y0MHOGH6IJBAGKywHdAlzH2Po3HWOmvONtNYddFbX8YX8nyYaQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8991dba1-00e5-4465-9cdc-60c6ded35805",
                            TwoFactorEnabled = false,
                            UserName = "ezgi@seeddata.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("MiniCommerce.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MiniCommerce.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MiniCommerce.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("MiniCommerce.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniCommerce.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MiniCommerce.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.Offer", b =>
                {
                    b.HasOne("MiniCommerce.Domain.Entities.Product", "Product")
                        .WithMany("Offers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniCommerce.Domain.Entities.User", "User")
                        .WithMany("Offers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.Product", b =>
                {
                    b.HasOne("MiniCommerce.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId");

                    b.HasOne("MiniCommerce.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniCommerce.Domain.Entities.Color", "Color")
                        .WithMany("Products")
                        .HasForeignKey("ColorId");

                    b.HasOne("MiniCommerce.Domain.Entities.Usage", "Usage")
                        .WithMany("Products")
                        .HasForeignKey("UsageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniCommerce.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Color");

                    b.Navigation("Usage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.Color", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.Product", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.Usage", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniCommerce.Domain.Entities.User", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
